# Generated by Django 5.0.4 on 2024-05-05 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_cadastrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('responsavel_1', models.CharField(max_length=150)),
                ('responsavel_2', models.CharField(blank=True, max_length=150)),
                ('telefone_1', models.CharField(max_length=20)),
                ('telefone_2', models.CharField(blank=True, max_length=20)),
                ('principais_servicos', models.CharField(max_length=300)),
                ('telefone_3', models.CharField(blank=True, max_length=20)),
                ('telefone_4', models.CharField(blank=True, max_length=20)),
                ('pessoa_referencia_1', models.CharField(blank=True, max_length=150)),
                ('pessoa_referencia_2', models.CharField(blank=True, max_length=150)),
                ('origem_do_encaminhamento', models.TextField(blank=True)),
                ('demanda_inicial', models.TextField(blank=True)),
                ('inicio_dos_atendimentos', models.TextField(blank=True)),
                ('log_de_cadastro', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_pessoa_atendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('log_de_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.CharField(max_length=150)),
                ('pessoa_atendida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_de_cadastro.dados_cadastrais')),
            ],
        ),
    ]
