# Generated by Django 5.0.4 on 2024-05-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_de_cadastro', '0002_alter_dados_cadastrais_idade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro_pessoa_atendida',
        ),
    ]
